{{- include "ace.validateValues" . -}}
{{- if not .Values.backend.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ace.backendSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ace.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if and (not .Values.externalDatabase.url) .Values.postgresql.enabled }}
  database-password: {{ .Values.postgresql.auth.password | quote }}
  {{- end }}
  {{- if .Values.backend.jwt.secret }}
  jwt-secret: {{ .Values.backend.jwt.secret | quote }}
  {{- end }}
  {{- if .Values.backend.jwt.privateKey }}
  jwt-private-key: {{ .Values.backend.jwt.privateKey | quote }}
  {{- end }}
  {{- if .Values.backend.jwt.publicKey }}
  jwt-public-key: {{ .Values.backend.jwt.publicKey | quote }}
  {{- end }}
  {{- if .Values.backend.posthog.apiKey }}
  posthog-api-key: {{ .Values.backend.posthog.apiKey | quote }}
  {{- end }}
  {{- if .Values.externalDatabase.password }}
  external-database-password: {{ .Values.externalDatabase.password | quote }}
  {{- end }}
{{- end }}
