{{- if .Values.vector.enabled -}}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "ace.fullname" . }}-vector
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ace.labels" . | nindent 4 }}
    app.kubernetes.io/component: vector
spec:
  selector:
    matchLabels:
      {{- include "ace.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: vector
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/vector/configmap.yaml") . | sha256sum }}
      labels:
        {{- include "ace.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: vector
    spec:
      {{- include "ace.imagePullSecrets" . | nindent 6 }}
      serviceAccountName: {{ include "ace.serviceAccountName" . }}
      containers:
        - name: vector
          image: "{{ .Values.vector.image.repository }}:{{ .Values.vector.image.tag }}"
          imagePullPolicy: {{ .Values.vector.image.pullPolicy }}
          args:
            - --config-dir
            - /etc/vector
          env:
            - name: VECTOR_SELF_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: VECTOR_SELF_POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: VECTOR_SELF_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
          ports:
            - name: prom-exporter
              containerPort: 9090
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /etc/vector
              readOnly: true
            - name: data
              mountPath: /vector-data-dir
            - name: var-log
              mountPath: /var/log
              readOnly: true
            - name: var-lib-docker
              mountPath: /var/lib/docker
              readOnly: true
          resources:
            {{- toYaml .Values.vector.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /health
              port: 8686
            initialDelaySeconds: 10
            periodSeconds: 15
            timeoutSeconds: 3
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8686
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
      terminationGracePeriodSeconds: 60
      tolerations:
        - effect: NoSchedule
          operator: Exists
      volumes:
        - name: config
          configMap:
            name: {{ include "ace.fullname" . }}-vector
        - name: data
          hostPath:
            path: /var/lib/vector
            type: DirectoryOrCreate
        - name: var-log
          hostPath:
            path: /var/log
        - name: var-lib-docker
          hostPath:
            path: /var/lib/docker
{{- end }}
